# Global settings applied to the whole site.
#
# “publish” is the directory to publish (relative to root of your repo),
# “command” is your build command,
# “base” is directory to change to before starting build. if you set base:
#    that is where we will look for package.json/.nvmrc/etc not repo root!

[build]
  base = "frontend"
  publish = "frontend/dist"
  command = "npm run build"
  environment = { LOAD_ENV = "staging" }

# Production context: All deploys to the main
# repository branch will inherit these settings.
[context.production]
  environment = { LOAD_ENV = "production" }

# SEE https://www.netlify.com/docs/redirects/
# rewrite from /pagename to /pagename.html is done automatically
# fallback to 404.html is done automatically
[[redirects]]
  from = "/api/*"
  to = "http://165.227.25.201:7777/:splat"
[[redirects]]
  from = "/gapi/*"
  to = "http://104.198.242.70/harberger-ads/graphql/:splat"
